# Generated by Django 5.1.1 on 2025-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Surname',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Photo',
            field=models.ImageField(blank=True, default='icon.jpg', null=True, upload_to='contacts_photo/'),
        ),
    ]
