# Generated by Django 5.1.1 on 2025-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_contact_surname_alter_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Photo',
            field=models.ImageField(blank=True, default='icon.jpg', upload_to='contacts_photo/'),
        ),
    ]
